---
# tasks file for bind
- name: install bind
  package:
    pkg: "{{ bind_packages }}"
    state: present

- name: configure bind
  template:
    src: "named.conf.j2"
    dest: "/etc/named.conf"
    owner: "root"
    group: "named"
    mode: "u=rw,g=r,o="
    setype: "named_conf_t"
    validate: "named-checkconf %s"
  notify: reload bind

- name: open firewall ports
  firewalld:
    service: dns
    permanent: yes
    state: enabled

- name: ensure bind is started and enabled on boot
  service:
    name: "{{ bind_daemon }}"
    state: "{{ bind_service_state }}"
    enabled: "{{ bind_service_enabled }}"
